// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: proto/review/review.proto

package review

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReviewInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	UserNickname  string                 `protobuf:"bytes,3,opt,name=user_nickname,json=userNickname,proto3" json:"user_nickname,omitempty"` // 冗余昵称，方便显示
	UserAvatar    string                 `protobuf:"bytes,4,opt,name=user_avatar,json=userAvatar,proto3" json:"user_avatar,omitempty"`       // 冗余头像
	Content       string                 `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`
	Star          int32                  `protobuf:"varint,6,opt,name=star,proto3" json:"star,omitempty"`
	Images        []string               `protobuf:"bytes,7,rep,name=images,proto3" json:"images,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	SkuName       string                 `protobuf:"bytes,9,opt,name=sku_name,json=skuName,proto3" json:"sku_name,omitempty"` // 购买时的规格名
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReviewInfo) Reset() {
	*x = ReviewInfo{}
	mi := &file_proto_review_review_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReviewInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReviewInfo) ProtoMessage() {}

func (x *ReviewInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_review_review_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReviewInfo.ProtoReflect.Descriptor instead.
func (*ReviewInfo) Descriptor() ([]byte, []int) {
	return file_proto_review_review_proto_rawDescGZIP(), []int{0}
}

func (x *ReviewInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ReviewInfo) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ReviewInfo) GetUserNickname() string {
	if x != nil {
		return x.UserNickname
	}
	return ""
}

func (x *ReviewInfo) GetUserAvatar() string {
	if x != nil {
		return x.UserAvatar
	}
	return ""
}

func (x *ReviewInfo) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ReviewInfo) GetStar() int32 {
	if x != nil {
		return x.Star
	}
	return 0
}

func (x *ReviewInfo) GetImages() []string {
	if x != nil {
		return x.Images
	}
	return nil
}

func (x *ReviewInfo) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *ReviewInfo) GetSkuName() string {
	if x != nil {
		return x.SkuName
	}
	return ""
}

type CreateReviewRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	OrderNo       string                 `protobuf:"bytes,2,opt,name=order_no,json=orderNo,proto3" json:"order_no,omitempty"`
	SkuId         int64                  `protobuf:"varint,3,opt,name=sku_id,json=skuId,proto3" json:"sku_id,omitempty"`
	ProductId     int64                  `protobuf:"varint,4,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Content       string                 `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`
	Star          int32                  `protobuf:"varint,6,opt,name=star,proto3" json:"star,omitempty"`
	Images        []string               `protobuf:"bytes,7,rep,name=images,proto3" json:"images,omitempty"` // 图片链接列表
	UserNickname  string                 `protobuf:"bytes,8,opt,name=user_nickname,json=userNickname,proto3" json:"user_nickname,omitempty"`
	UserAvatar    string                 `protobuf:"bytes,9,opt,name=user_avatar,json=userAvatar,proto3" json:"user_avatar,omitempty"`
	SkuName       string                 `protobuf:"bytes,10,opt,name=sku_name,json=skuName,proto3" json:"sku_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateReviewRequest) Reset() {
	*x = CreateReviewRequest{}
	mi := &file_proto_review_review_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateReviewRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateReviewRequest) ProtoMessage() {}

func (x *CreateReviewRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_review_review_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateReviewRequest.ProtoReflect.Descriptor instead.
func (*CreateReviewRequest) Descriptor() ([]byte, []int) {
	return file_proto_review_review_proto_rawDescGZIP(), []int{1}
}

func (x *CreateReviewRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CreateReviewRequest) GetOrderNo() string {
	if x != nil {
		return x.OrderNo
	}
	return ""
}

func (x *CreateReviewRequest) GetSkuId() int64 {
	if x != nil {
		return x.SkuId
	}
	return 0
}

func (x *CreateReviewRequest) GetProductId() int64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *CreateReviewRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *CreateReviewRequest) GetStar() int32 {
	if x != nil {
		return x.Star
	}
	return 0
}

func (x *CreateReviewRequest) GetImages() []string {
	if x != nil {
		return x.Images
	}
	return nil
}

func (x *CreateReviewRequest) GetUserNickname() string {
	if x != nil {
		return x.UserNickname
	}
	return ""
}

func (x *CreateReviewRequest) GetUserAvatar() string {
	if x != nil {
		return x.UserAvatar
	}
	return ""
}

func (x *CreateReviewRequest) GetSkuName() string {
	if x != nil {
		return x.SkuName
	}
	return ""
}

type CreateReviewResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReviewId      int64                  `protobuf:"varint,1,opt,name=review_id,json=reviewId,proto3" json:"review_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateReviewResponse) Reset() {
	*x = CreateReviewResponse{}
	mi := &file_proto_review_review_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateReviewResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateReviewResponse) ProtoMessage() {}

func (x *CreateReviewResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_review_review_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateReviewResponse.ProtoReflect.Descriptor instead.
func (*CreateReviewResponse) Descriptor() ([]byte, []int) {
	return file_proto_review_review_proto_rawDescGZIP(), []int{2}
}

func (x *CreateReviewResponse) GetReviewId() int64 {
	if x != nil {
		return x.ReviewId
	}
	return 0
}

type ListReviewsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     int64                  `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListReviewsRequest) Reset() {
	*x = ListReviewsRequest{}
	mi := &file_proto_review_review_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListReviewsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListReviewsRequest) ProtoMessage() {}

func (x *ListReviewsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_review_review_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListReviewsRequest.ProtoReflect.Descriptor instead.
func (*ListReviewsRequest) Descriptor() ([]byte, []int) {
	return file_proto_review_review_proto_rawDescGZIP(), []int{3}
}

func (x *ListReviewsRequest) GetProductId() int64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *ListReviewsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListReviewsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListReviewsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reviews       []*ReviewInfo          `protobuf:"bytes,1,rep,name=reviews,proto3" json:"reviews,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	AverageStar   float32                `protobuf:"fixed32,3,opt,name=average_star,json=averageStar,proto3" json:"average_star,omitempty"` // 该商品的平均分
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListReviewsResponse) Reset() {
	*x = ListReviewsResponse{}
	mi := &file_proto_review_review_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListReviewsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListReviewsResponse) ProtoMessage() {}

func (x *ListReviewsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_review_review_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListReviewsResponse.ProtoReflect.Descriptor instead.
func (*ListReviewsResponse) Descriptor() ([]byte, []int) {
	return file_proto_review_review_proto_rawDescGZIP(), []int{4}
}

func (x *ListReviewsResponse) GetReviews() []*ReviewInfo {
	if x != nil {
		return x.Reviews
	}
	return nil
}

func (x *ListReviewsResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListReviewsResponse) GetAverageStar() float32 {
	if x != nil {
		return x.AverageStar
	}
	return 0
}

type CheckReviewStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	OrderNo       string                 `protobuf:"bytes,2,opt,name=order_no,json=orderNo,proto3" json:"order_no,omitempty"`
	SkuId         int64                  `protobuf:"varint,3,opt,name=sku_id,json=skuId,proto3" json:"sku_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckReviewStatusRequest) Reset() {
	*x = CheckReviewStatusRequest{}
	mi := &file_proto_review_review_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckReviewStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckReviewStatusRequest) ProtoMessage() {}

func (x *CheckReviewStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_review_review_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckReviewStatusRequest.ProtoReflect.Descriptor instead.
func (*CheckReviewStatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_review_review_proto_rawDescGZIP(), []int{5}
}

func (x *CheckReviewStatusRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CheckReviewStatusRequest) GetOrderNo() string {
	if x != nil {
		return x.OrderNo
	}
	return ""
}

func (x *CheckReviewStatusRequest) GetSkuId() int64 {
	if x != nil {
		return x.SkuId
	}
	return 0
}

type CheckReviewStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HasReviewed   bool                   `protobuf:"varint,1,opt,name=has_reviewed,json=hasReviewed,proto3" json:"has_reviewed,omitempty"`
	ReviewId      int64                  `protobuf:"varint,2,opt,name=review_id,json=reviewId,proto3" json:"review_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckReviewStatusResponse) Reset() {
	*x = CheckReviewStatusResponse{}
	mi := &file_proto_review_review_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckReviewStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckReviewStatusResponse) ProtoMessage() {}

func (x *CheckReviewStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_review_review_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckReviewStatusResponse.ProtoReflect.Descriptor instead.
func (*CheckReviewStatusResponse) Descriptor() ([]byte, []int) {
	return file_proto_review_review_proto_rawDescGZIP(), []int{6}
}

func (x *CheckReviewStatusResponse) GetHasReviewed() bool {
	if x != nil {
		return x.HasReviewed
	}
	return false
}

func (x *CheckReviewStatusResponse) GetReviewId() int64 {
	if x != nil {
		return x.ReviewId
	}
	return 0
}

var File_proto_review_review_proto protoreflect.FileDescriptor

const file_proto_review_review_proto_rawDesc = "" +
	"\n" +
	"\x19proto/review/review.proto\x12\x06review\"\xfb\x01\n" +
	"\n" +
	"ReviewInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12#\n" +
	"\ruser_nickname\x18\x03 \x01(\tR\fuserNickname\x12\x1f\n" +
	"\vuser_avatar\x18\x04 \x01(\tR\n" +
	"userAvatar\x12\x18\n" +
	"\acontent\x18\x05 \x01(\tR\acontent\x12\x12\n" +
	"\x04star\x18\x06 \x01(\x05R\x04star\x12\x16\n" +
	"\x06images\x18\a \x03(\tR\x06images\x12\x1d\n" +
	"\n" +
	"created_at\x18\b \x01(\tR\tcreatedAt\x12\x19\n" +
	"\bsku_name\x18\t \x01(\tR\askuName\"\xa6\x02\n" +
	"\x13CreateReviewRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x19\n" +
	"\border_no\x18\x02 \x01(\tR\aorderNo\x12\x15\n" +
	"\x06sku_id\x18\x03 \x01(\x03R\x05skuId\x12\x1d\n" +
	"\n" +
	"product_id\x18\x04 \x01(\x03R\tproductId\x12\x18\n" +
	"\acontent\x18\x05 \x01(\tR\acontent\x12\x12\n" +
	"\x04star\x18\x06 \x01(\x05R\x04star\x12\x16\n" +
	"\x06images\x18\a \x03(\tR\x06images\x12#\n" +
	"\ruser_nickname\x18\b \x01(\tR\fuserNickname\x12\x1f\n" +
	"\vuser_avatar\x18\t \x01(\tR\n" +
	"userAvatar\x12\x19\n" +
	"\bsku_name\x18\n" +
	" \x01(\tR\askuName\"3\n" +
	"\x14CreateReviewResponse\x12\x1b\n" +
	"\treview_id\x18\x01 \x01(\x03R\breviewId\"d\n" +
	"\x12ListReviewsRequest\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\x03R\tproductId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\"|\n" +
	"\x13ListReviewsResponse\x12,\n" +
	"\areviews\x18\x01 \x03(\v2\x12.review.ReviewInfoR\areviews\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\x12!\n" +
	"\faverage_star\x18\x03 \x01(\x02R\vaverageStar\"e\n" +
	"\x18CheckReviewStatusRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x19\n" +
	"\border_no\x18\x02 \x01(\tR\aorderNo\x12\x15\n" +
	"\x06sku_id\x18\x03 \x01(\x03R\x05skuId\"[\n" +
	"\x19CheckReviewStatusResponse\x12!\n" +
	"\fhas_reviewed\x18\x01 \x01(\bR\vhasReviewed\x12\x1b\n" +
	"\treview_id\x18\x02 \x01(\x03R\breviewId2\xfc\x01\n" +
	"\rReviewService\x12I\n" +
	"\fCreateReview\x12\x1b.review.CreateReviewRequest\x1a\x1c.review.CreateReviewResponse\x12F\n" +
	"\vListReviews\x12\x1a.review.ListReviewsRequest\x1a\x1b.review.ListReviewsResponse\x12X\n" +
	"\x11CheckReviewStatus\x12 .review.CheckReviewStatusRequest\x1a!.review.CheckReviewStatusResponseB\x1bZ\x19go-ecommerce/proto/reviewb\x06proto3"

var (
	file_proto_review_review_proto_rawDescOnce sync.Once
	file_proto_review_review_proto_rawDescData []byte
)

func file_proto_review_review_proto_rawDescGZIP() []byte {
	file_proto_review_review_proto_rawDescOnce.Do(func() {
		file_proto_review_review_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_review_review_proto_rawDesc), len(file_proto_review_review_proto_rawDesc)))
	})
	return file_proto_review_review_proto_rawDescData
}

var file_proto_review_review_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proto_review_review_proto_goTypes = []any{
	(*ReviewInfo)(nil),                // 0: review.ReviewInfo
	(*CreateReviewRequest)(nil),       // 1: review.CreateReviewRequest
	(*CreateReviewResponse)(nil),      // 2: review.CreateReviewResponse
	(*ListReviewsRequest)(nil),        // 3: review.ListReviewsRequest
	(*ListReviewsResponse)(nil),       // 4: review.ListReviewsResponse
	(*CheckReviewStatusRequest)(nil),  // 5: review.CheckReviewStatusRequest
	(*CheckReviewStatusResponse)(nil), // 6: review.CheckReviewStatusResponse
}
var file_proto_review_review_proto_depIdxs = []int32{
	0, // 0: review.ListReviewsResponse.reviews:type_name -> review.ReviewInfo
	1, // 1: review.ReviewService.CreateReview:input_type -> review.CreateReviewRequest
	3, // 2: review.ReviewService.ListReviews:input_type -> review.ListReviewsRequest
	5, // 3: review.ReviewService.CheckReviewStatus:input_type -> review.CheckReviewStatusRequest
	2, // 4: review.ReviewService.CreateReview:output_type -> review.CreateReviewResponse
	4, // 5: review.ReviewService.ListReviews:output_type -> review.ListReviewsResponse
	6, // 6: review.ReviewService.CheckReviewStatus:output_type -> review.CheckReviewStatusResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_review_review_proto_init() }
func file_proto_review_review_proto_init() {
	if File_proto_review_review_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_review_review_proto_rawDesc), len(file_proto_review_review_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_review_review_proto_goTypes,
		DependencyIndexes: file_proto_review_review_proto_depIdxs,
		MessageInfos:      file_proto_review_review_proto_msgTypes,
	}.Build()
	File_proto_review_review_proto = out.File
	file_proto_review_review_proto_goTypes = nil
	file_proto_review_review_proto_depIdxs = nil
}
