// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: proto/admin/admin.proto

package admin

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 消息定义
type StatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatsRequest) Reset() {
	*x = StatsRequest{}
	mi := &file_proto_admin_admin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsRequest) ProtoMessage() {}

func (x *StatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_admin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsRequest.ProtoReflect.Descriptor instead.
func (*StatsRequest) Descriptor() ([]byte, []int) {
	return file_proto_admin_admin_proto_rawDescGZIP(), []int{0}
}

type StatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TotalSales    float32                `protobuf:"fixed32,1,opt,name=total_sales,json=totalSales,proto3" json:"total_sales,omitempty"`
	OrderCount    int32                  `protobuf:"varint,2,opt,name=order_count,json=orderCount,proto3" json:"order_count,omitempty"`
	UserCount     int32                  `protobuf:"varint,3,opt,name=user_count,json=userCount,proto3" json:"user_count,omitempty"`
	ProductCount  int32                  `protobuf:"varint,4,opt,name=product_count,json=productCount,proto3" json:"product_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatsResponse) Reset() {
	*x = StatsResponse{}
	mi := &file_proto_admin_admin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsResponse) ProtoMessage() {}

func (x *StatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_admin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsResponse.ProtoReflect.Descriptor instead.
func (*StatsResponse) Descriptor() ([]byte, []int) {
	return file_proto_admin_admin_proto_rawDescGZIP(), []int{1}
}

func (x *StatsResponse) GetTotalSales() float32 {
	if x != nil {
		return x.TotalSales
	}
	return 0
}

func (x *StatsResponse) GetOrderCount() int32 {
	if x != nil {
		return x.OrderCount
	}
	return 0
}

func (x *StatsResponse) GetUserCount() int32 {
	if x != nil {
		return x.UserCount
	}
	return 0
}

func (x *StatsResponse) GetProductCount() int32 {
	if x != nil {
		return x.ProductCount
	}
	return 0
}

type ListUsersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUsersRequest) Reset() {
	*x = ListUsersRequest{}
	mi := &file_proto_admin_admin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUsersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUsersRequest) ProtoMessage() {}

func (x *ListUsersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_admin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUsersRequest.ProtoReflect.Descriptor instead.
func (*ListUsersRequest) Descriptor() ([]byte, []int) {
	return file_proto_admin_admin_proto_rawDescGZIP(), []int{2}
}

func (x *ListUsersRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListUsersRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type UserInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Nickname      string                 `protobuf:"bytes,3,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Mobile        string                 `protobuf:"bytes,4,opt,name=mobile,proto3" json:"mobile,omitempty"`
	Role          string                 `protobuf:"bytes,5,opt,name=role,proto3" json:"role,omitempty"`
	IsDisabled    bool                   `protobuf:"varint,6,opt,name=is_disabled,json=isDisabled,proto3" json:"is_disabled,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserInfo) Reset() {
	*x = UserInfo{}
	mi := &file_proto_admin_admin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInfo) ProtoMessage() {}

func (x *UserInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_admin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInfo.ProtoReflect.Descriptor instead.
func (*UserInfo) Descriptor() ([]byte, []int) {
	return file_proto_admin_admin_proto_rawDescGZIP(), []int{3}
}

func (x *UserInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UserInfo) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UserInfo) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *UserInfo) GetMobile() string {
	if x != nil {
		return x.Mobile
	}
	return ""
}

func (x *UserInfo) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *UserInfo) GetIsDisabled() bool {
	if x != nil {
		return x.IsDisabled
	}
	return false
}

func (x *UserInfo) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type ListUsersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*UserInfo            `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUsersResponse) Reset() {
	*x = ListUsersResponse{}
	mi := &file_proto_admin_admin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUsersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUsersResponse) ProtoMessage() {}

func (x *ListUsersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_admin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUsersResponse.ProtoReflect.Descriptor instead.
func (*ListUsersResponse) Descriptor() ([]byte, []int) {
	return file_proto_admin_admin_proto_rawDescGZIP(), []int{4}
}

func (x *ListUsersResponse) GetUsers() []*UserInfo {
	if x != nil {
		return x.Users
	}
	return nil
}

func (x *ListUsersResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type ToggleStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Disabled      bool                   `protobuf:"varint,2,opt,name=disabled,proto3" json:"disabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToggleStatusRequest) Reset() {
	*x = ToggleStatusRequest{}
	mi := &file_proto_admin_admin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToggleStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToggleStatusRequest) ProtoMessage() {}

func (x *ToggleStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_admin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToggleStatusRequest.ProtoReflect.Descriptor instead.
func (*ToggleStatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_admin_admin_proto_rawDescGZIP(), []int{5}
}

func (x *ToggleStatusRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ToggleStatusRequest) GetDisabled() bool {
	if x != nil {
		return x.Disabled
	}
	return false
}

type ToggleStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToggleStatusResponse) Reset() {
	*x = ToggleStatusResponse{}
	mi := &file_proto_admin_admin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToggleStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToggleStatusResponse) ProtoMessage() {}

func (x *ToggleStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_admin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToggleStatusResponse.ProtoReflect.Descriptor instead.
func (*ToggleStatusResponse) Descriptor() ([]byte, []int) {
	return file_proto_admin_admin_proto_rawDescGZIP(), []int{6}
}

func (x *ToggleStatusResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type ListAllProductsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAllProductsRequest) Reset() {
	*x = ListAllProductsRequest{}
	mi := &file_proto_admin_admin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAllProductsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAllProductsRequest) ProtoMessage() {}

func (x *ListAllProductsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_admin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAllProductsRequest.ProtoReflect.Descriptor instead.
func (*ListAllProductsRequest) Descriptor() ([]byte, []int) {
	return file_proto_admin_admin_proto_rawDescGZIP(), []int{7}
}

func (x *ListAllProductsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListAllProductsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type AdminProductInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Price         float32                `protobuf:"fixed32,3,opt,name=price,proto3" json:"price,omitempty"`
	Stock         int32                  `protobuf:"varint,4,opt,name=stock,proto3" json:"stock,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminProductInfo) Reset() {
	*x = AdminProductInfo{}
	mi := &file_proto_admin_admin_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminProductInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminProductInfo) ProtoMessage() {}

func (x *AdminProductInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_admin_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminProductInfo.ProtoReflect.Descriptor instead.
func (*AdminProductInfo) Descriptor() ([]byte, []int) {
	return file_proto_admin_admin_proto_rawDescGZIP(), []int{8}
}

func (x *AdminProductInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AdminProductInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AdminProductInfo) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *AdminProductInfo) GetStock() int32 {
	if x != nil {
		return x.Stock
	}
	return 0
}

type ListAllProductsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Products      []*AdminProductInfo    `protobuf:"bytes,1,rep,name=products,proto3" json:"products,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAllProductsResponse) Reset() {
	*x = ListAllProductsResponse{}
	mi := &file_proto_admin_admin_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAllProductsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAllProductsResponse) ProtoMessage() {}

func (x *ListAllProductsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_admin_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAllProductsResponse.ProtoReflect.Descriptor instead.
func (*ListAllProductsResponse) Descriptor() ([]byte, []int) {
	return file_proto_admin_admin_proto_rawDescGZIP(), []int{9}
}

func (x *ListAllProductsResponse) GetProducts() []*AdminProductInfo {
	if x != nil {
		return x.Products
	}
	return nil
}

func (x *ListAllProductsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type UpdateProductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Price         float32                `protobuf:"fixed32,2,opt,name=price,proto3" json:"price,omitempty"`
	Stock         int32                  `protobuf:"varint,3,opt,name=stock,proto3" json:"stock,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProductRequest) Reset() {
	*x = UpdateProductRequest{}
	mi := &file_proto_admin_admin_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProductRequest) ProtoMessage() {}

func (x *UpdateProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_admin_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProductRequest.ProtoReflect.Descriptor instead.
func (*UpdateProductRequest) Descriptor() ([]byte, []int) {
	return file_proto_admin_admin_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateProductRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateProductRequest) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *UpdateProductRequest) GetStock() int32 {
	if x != nil {
		return x.Stock
	}
	return 0
}

type UpdateProductResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProductResponse) Reset() {
	*x = UpdateProductResponse{}
	mi := &file_proto_admin_admin_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProductResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProductResponse) ProtoMessage() {}

func (x *UpdateProductResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_admin_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProductResponse.ProtoReflect.Descriptor instead.
func (*UpdateProductResponse) Descriptor() ([]byte, []int) {
	return file_proto_admin_admin_proto_rawDescGZIP(), []int{11}
}

func (x *UpdateProductResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type ShipOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderNo       string                 `protobuf:"bytes,1,opt,name=order_no,json=orderNo,proto3" json:"order_no,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShipOrderRequest) Reset() {
	*x = ShipOrderRequest{}
	mi := &file_proto_admin_admin_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShipOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShipOrderRequest) ProtoMessage() {}

func (x *ShipOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_admin_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShipOrderRequest.ProtoReflect.Descriptor instead.
func (*ShipOrderRequest) Descriptor() ([]byte, []int) {
	return file_proto_admin_admin_proto_rawDescGZIP(), []int{12}
}

func (x *ShipOrderRequest) GetOrderNo() string {
	if x != nil {
		return x.OrderNo
	}
	return ""
}

type ShipOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShipOrderResponse) Reset() {
	*x = ShipOrderResponse{}
	mi := &file_proto_admin_admin_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShipOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShipOrderResponse) ProtoMessage() {}

func (x *ShipOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_admin_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShipOrderResponse.ProtoReflect.Descriptor instead.
func (*ShipOrderResponse) Descriptor() ([]byte, []int) {
	return file_proto_admin_admin_proto_rawDescGZIP(), []int{13}
}

func (x *ShipOrderResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_proto_admin_admin_proto protoreflect.FileDescriptor

const file_proto_admin_admin_proto_rawDesc = "" +
	"\n" +
	"\x17proto/admin/admin.proto\x12\x05admin\"\x0e\n" +
	"\fStatsRequest\"\x95\x01\n" +
	"\rStatsResponse\x12\x1f\n" +
	"\vtotal_sales\x18\x01 \x01(\x02R\n" +
	"totalSales\x12\x1f\n" +
	"\vorder_count\x18\x02 \x01(\x05R\n" +
	"orderCount\x12\x1d\n" +
	"\n" +
	"user_count\x18\x03 \x01(\x05R\tuserCount\x12#\n" +
	"\rproduct_count\x18\x04 \x01(\x05R\fproductCount\"C\n" +
	"\x10ListUsersRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\"\xbe\x01\n" +
	"\bUserInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x1a\n" +
	"\bnickname\x18\x03 \x01(\tR\bnickname\x12\x16\n" +
	"\x06mobile\x18\x04 \x01(\tR\x06mobile\x12\x12\n" +
	"\x04role\x18\x05 \x01(\tR\x04role\x12\x1f\n" +
	"\vis_disabled\x18\x06 \x01(\bR\n" +
	"isDisabled\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\tR\tcreatedAt\"P\n" +
	"\x11ListUsersResponse\x12%\n" +
	"\x05users\x18\x01 \x03(\v2\x0f.admin.UserInfoR\x05users\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"J\n" +
	"\x13ToggleStatusRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1a\n" +
	"\bdisabled\x18\x02 \x01(\bR\bdisabled\"0\n" +
	"\x14ToggleStatusResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"I\n" +
	"\x16ListAllProductsRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\"b\n" +
	"\x10AdminProductInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05price\x18\x03 \x01(\x02R\x05price\x12\x14\n" +
	"\x05stock\x18\x04 \x01(\x05R\x05stock\"d\n" +
	"\x17ListAllProductsResponse\x123\n" +
	"\bproducts\x18\x01 \x03(\v2\x17.admin.AdminProductInfoR\bproducts\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"R\n" +
	"\x14UpdateProductRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05price\x18\x02 \x01(\x02R\x05price\x12\x14\n" +
	"\x05stock\x18\x03 \x01(\x05R\x05stock\"1\n" +
	"\x15UpdateProductResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"-\n" +
	"\x10ShipOrderRequest\x12\x19\n" +
	"\border_no\x18\x01 \x01(\tR\aorderNo\"-\n" +
	"\x11ShipOrderResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\xb9\x03\n" +
	"\fAdminService\x12>\n" +
	"\x11GetDashboardStats\x12\x13.admin.StatsRequest\x1a\x14.admin.StatsResponse\x12>\n" +
	"\tListUsers\x12\x17.admin.ListUsersRequest\x1a\x18.admin.ListUsersResponse\x12K\n" +
	"\x10ToggleUserStatus\x12\x1a.admin.ToggleStatusRequest\x1a\x1b.admin.ToggleStatusResponse\x12P\n" +
	"\x0fListAllProducts\x12\x1d.admin.ListAllProductsRequest\x1a\x1e.admin.ListAllProductsResponse\x12J\n" +
	"\rUpdateProduct\x12\x1b.admin.UpdateProductRequest\x1a\x1c.admin.UpdateProductResponse\x12>\n" +
	"\tShipOrder\x12\x17.admin.ShipOrderRequest\x1a\x18.admin.ShipOrderResponseB\x1aZ\x18go-ecommerce/proto/adminb\x06proto3"

var (
	file_proto_admin_admin_proto_rawDescOnce sync.Once
	file_proto_admin_admin_proto_rawDescData []byte
)

func file_proto_admin_admin_proto_rawDescGZIP() []byte {
	file_proto_admin_admin_proto_rawDescOnce.Do(func() {
		file_proto_admin_admin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_admin_admin_proto_rawDesc), len(file_proto_admin_admin_proto_rawDesc)))
	})
	return file_proto_admin_admin_proto_rawDescData
}

var file_proto_admin_admin_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_proto_admin_admin_proto_goTypes = []any{
	(*StatsRequest)(nil),            // 0: admin.StatsRequest
	(*StatsResponse)(nil),           // 1: admin.StatsResponse
	(*ListUsersRequest)(nil),        // 2: admin.ListUsersRequest
	(*UserInfo)(nil),                // 3: admin.UserInfo
	(*ListUsersResponse)(nil),       // 4: admin.ListUsersResponse
	(*ToggleStatusRequest)(nil),     // 5: admin.ToggleStatusRequest
	(*ToggleStatusResponse)(nil),    // 6: admin.ToggleStatusResponse
	(*ListAllProductsRequest)(nil),  // 7: admin.ListAllProductsRequest
	(*AdminProductInfo)(nil),        // 8: admin.AdminProductInfo
	(*ListAllProductsResponse)(nil), // 9: admin.ListAllProductsResponse
	(*UpdateProductRequest)(nil),    // 10: admin.UpdateProductRequest
	(*UpdateProductResponse)(nil),   // 11: admin.UpdateProductResponse
	(*ShipOrderRequest)(nil),        // 12: admin.ShipOrderRequest
	(*ShipOrderResponse)(nil),       // 13: admin.ShipOrderResponse
}
var file_proto_admin_admin_proto_depIdxs = []int32{
	3,  // 0: admin.ListUsersResponse.users:type_name -> admin.UserInfo
	8,  // 1: admin.ListAllProductsResponse.products:type_name -> admin.AdminProductInfo
	0,  // 2: admin.AdminService.GetDashboardStats:input_type -> admin.StatsRequest
	2,  // 3: admin.AdminService.ListUsers:input_type -> admin.ListUsersRequest
	5,  // 4: admin.AdminService.ToggleUserStatus:input_type -> admin.ToggleStatusRequest
	7,  // 5: admin.AdminService.ListAllProducts:input_type -> admin.ListAllProductsRequest
	10, // 6: admin.AdminService.UpdateProduct:input_type -> admin.UpdateProductRequest
	12, // 7: admin.AdminService.ShipOrder:input_type -> admin.ShipOrderRequest
	1,  // 8: admin.AdminService.GetDashboardStats:output_type -> admin.StatsResponse
	4,  // 9: admin.AdminService.ListUsers:output_type -> admin.ListUsersResponse
	6,  // 10: admin.AdminService.ToggleUserStatus:output_type -> admin.ToggleStatusResponse
	9,  // 11: admin.AdminService.ListAllProducts:output_type -> admin.ListAllProductsResponse
	11, // 12: admin.AdminService.UpdateProduct:output_type -> admin.UpdateProductResponse
	13, // 13: admin.AdminService.ShipOrder:output_type -> admin.ShipOrderResponse
	8,  // [8:14] is the sub-list for method output_type
	2,  // [2:8] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_proto_admin_admin_proto_init() }
func file_proto_admin_admin_proto_init() {
	if File_proto_admin_admin_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_admin_admin_proto_rawDesc), len(file_proto_admin_admin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_admin_admin_proto_goTypes,
		DependencyIndexes: file_proto_admin_admin_proto_depIdxs,
		MessageInfos:      file_proto_admin_admin_proto_msgTypes,
	}.Build()
	File_proto_admin_admin_proto = out.File
	file_proto_admin_admin_proto_goTypes = nil
	file_proto_admin_admin_proto_depIdxs = nil
}
